### ISSUE TITLE
Pow() throws exception when real part is 0 and imaginary part is +/-1

### ISSUE THREAD

**Issue by morphx666** [AdamWhiteHat/BigComplex#1]
**Description**
`BigComplex.Pow()` throws `System.OverflowException` (The value is not a number) whenever the real part is 0 and the imaginary part is +/-1

**Error/Exception Message**
``` csharp
Exception has occurred: CLR/System.OverflowException
An exception of type 'System.OverflowException' occurred in System.Runtime.Numerics.dll but was not handled in user code: 'The value is not a number.'
   at System.Numerics.BigInteger..ctor(Double value)
   at System.Numerics.BigInteger.op_Explicit(Double value)
   at ExtendedNumerics.BigComplex.Pow(BigComplex value, BigComplex power)
   at mandelbrot.MainForm.<>c__DisplayClass21_2.<RenderMandelbrot>b__1(Double x, ParallelLoopState state, Int64 sx) in c:\Users\XavierFlix\Dropbox\Projects\Experiments\mandelbrot\mandelbrot\MainForm.jeto.cs:line 216
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__2(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

```
**Expected Behavior**
For example (0+1i) ^ (2) should return (-1, 0)
(0-1i) ^ (3) should return (0, -1)
...and so on

**Actual Behavior**
A `System.OverflowException` exception is thrown

**Steps To Reproduce**
``` csharp
BigComplex c = new(BigInteger.Zero, -BigInteger.One);
double p = 2.1;
BigComplex result = BigComplex.Pow(c, p);
```

**Comment by AdamWhiteHat** [comment]
There this should be fixed. 
I added a test to cover this case.

Thanks for bringing this to my attention. 

If you are satisfied, feel free to close the issue. 
Or do nothing, that's cool too. If I hear nothing further from you in a few days, I will consider the matter resolve and close the issue.

**Comment by morphx666** [comment]
Thank you for the prompt response. I will test it later today and let you know.

**Comment by AdamWhiteHat** [comment]
I question the utility of a BigComplex library that uses BigInteger for its real and imaginary part. 
I see you are using this library for making a Mandelbrot set. That's awesome.
I suspect, although am not certain, that you will find that a complex number that forces its components to be whole-number integers to be ill suited for this purpose. If you find that to be the case, I encourage you to try out [the other branch on this repo called BigDecimal-Implementation](https://github.com/AdamWhiteHat/BigComplex/tree/BigDecimal-Implementation), which contains the same code, just with every instance of BigInteger replaced with my arbitrary precision floating point number type [BigDecimal](https://github.com/AdamWhiteHat/BigDecimal).

In fact, I am thinking about making this branch the main branch because, after all, the components that make up a complex number are called the **real** part and the imaginary part, and not the integer part and the imaginary part.

**Comment by morphx666** [comment]
Well, the good news is no more exceptions! Thank you!
The bad news is that I can't get it to work... but, I guess that's on me ;)

I initially tried using BigDecimal but never finished it as I thought using BigComplex would be easier... but I guess I could give it another try.
